import Foundation

/// A streaming MessagePack input cursor, used by ``MessagePackSerializable``
/// conformances (typically generated by the `@MessagePackSerializable` macro)
/// to read values.
///
/// The reader walks a borrowed raw byte buffer; it never copies the input.
/// Each `read` method consumes one value and throws
/// ``MessagePackError/typeMismatch(expected:format:)`` if the next value on
/// the wire has a different type, leaving the reader positioned at that value.
///
/// The reader is noncopyable: it borrows memory owned by the enclosing
/// `deserialize` call, so a copy could not safely outlive it.
///
/// Reading a container header enters that container; balance it with
/// ``endContainer()`` after reading the container's values. Nesting deeper
/// than ``maxDepth`` throws ``MessagePackError/depthLimitExceeded``, which
/// bounds the recursion hostile input can drive through recursively defined
/// `MessagePackSerializable` types.
public struct MessagePackReader: ~Copyable {
    /// Maximum container nesting accepted while decoding, matching
    /// ``MessagePackDecoder``. Bounds stack use against hostile input aimed
    /// at recursive types, including on the small stacks of cooperative-pool
    /// threads.
    public static let maxDepth = 128

    @usableFromInline
    var parser: MessagePackSerializer.Parser

    /// The number of containers currently entered and not yet ended.
    @usableFromInline
    var depth = 0

    /// Creates a reader over `buffer`, which must stay valid while the
    /// reader is used.
    @usableFromInline
    init(buffer: UnsafeRawBufferPointer) {
        self.parser = MessagePackSerializer.Parser(buffer: buffer)
    }

    /// True when every input byte has been consumed.
    @inlinable
    public var isAtEnd: Bool {
        parser.offset == parser.count
    }

    // MARK: Scalars

    /// Consumes a nil marker if the next value is nil, and returns whether it
    /// did. Used to decode optionals.
    @inlinable
    public mutating func readNilIfPresent() -> Bool {
        parser.readRawNil()
    }

    @inlinable
    public mutating func readBool() throws(MessagePackError) -> Bool {
        guard let value = try parser.readRawBool() else {
            throw MessagePackError.typeMismatch(expected: "bool", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads any integer format into `T`, throwing
    /// ``MessagePackError/integerOverflow`` if the value does not fit.
    @inlinable
    public mutating func readInteger<T: FixedWidthInteger>(
        _ type: T.Type = T.self
    ) throws(MessagePackError) -> T {
        guard let raw = try parser.readRawInteger() else {
            throw MessagePackError.typeMismatch(
                expected: "integer", format: try parser.peekFormat())
        }
        switch raw {
        case .signed(let value):
            guard let converted = T(exactly: value) else {
                throw MessagePackError.integerOverflow
            }
            return converted
        case .unsigned(let value):
            guard let converted = T(exactly: value) else {
                throw MessagePackError.integerOverflow
            }
            return converted
        }
    }

    /// Reads a float 32/64 (or, leniently, any integer) as a `Double`.
    @inlinable
    public mutating func readDouble() throws(MessagePackError) -> Double {
        guard let value = try parser.readRawDouble() else {
            throw MessagePackError.typeMismatch(expected: "float", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads a float 32/64 (or, leniently, any integer) as a `Float`.
    /// float 64 values are rounded to the nearest `Float`; finite values that
    /// overflow `Float`'s range throw ``MessagePackError/floatOverflow``
    /// (matching ``MessagePackDecoder``) instead of becoming infinite.
    @inlinable
    public mutating func readFloat() throws(MessagePackError) -> Float {
        let value = try readDouble()
        let narrowed = Float(value)
        guard !(narrowed.isInfinite && value.isFinite) else {
            throw MessagePackError.floatOverflow
        }
        return narrowed
    }

    /// Reads a string, throwing ``MessagePackError/invalidUTF8`` if its
    /// bytes are not valid UTF-8; ``readStringBytes()`` reads them as they are.
    @inlinable
    public mutating func readString() throws(MessagePackError) -> String {
        guard let value = try parser.readRawString() else {
            throw MessagePackError.typeMismatch(expected: "string", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads a string's bytes as they are on the wire, without validating
    /// them as UTF-8.
    ///
    /// The spec lets a string hold an invalid byte sequence, leaves what a
    /// deserializer does with one to the implementation (``readString()``
    /// rejects it), and asks deserializers to give applications the original
    /// bytes so they can decide how to handle it: this is that access.
    @inlinable
    public mutating func readStringBytes() throws(MessagePackError) -> Data {
        guard let bytes = try parser.readRawStringBytes() else {
            throw MessagePackError.typeMismatch(expected: "string", format: try parser.peekFormat())
        }
        return Data(buffer: bytes)
    }

    /// Reads a binary (bin 8/16/32) payload.
    @inlinable
    public mutating func readBinary() throws(MessagePackError) -> Data {
        guard let value = try parser.readRawBinary() else {
            throw MessagePackError.typeMismatch(expected: "binary", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads a map key (a string value) and hands its raw UTF-8 bytes to
    /// `match` without materializing a `String`, returning `match`'s result.
    ///
    /// Generated `init(messagePack:)` implementations use this to match
    /// field names by direct byte comparison (see ``key(_:matches:)``).
    /// When `match` returns `nil` (unknown key), the bytes are validated so
    /// malformed keys still throw ``MessagePackError/invalidUTF8`` exactly
    /// like ``readString()`` would; a matched key is byte-equal to a known
    /// valid key and needs no validation. Throws
    /// ``MessagePackError/typeMismatch(expected:format:)`` if the next value
    /// is not a string, leaving the reader positioned at that value.
    @inlinable
    public mutating func readKey(
        matchedBy match: (UnsafeBufferPointer<UInt8>) -> Int?
    ) throws(MessagePackError) -> Int? {
        guard let bytes = try parser.readRawStringBytes() else {
            throw MessagePackError.typeMismatch(expected: "string", format: try parser.peekFormat())
        }
        guard let index = match(bytes) else {
            guard messagePackMakeString(bytes) != nil else {
                throw MessagePackError.invalidUTF8
            }
            return nil
        }
        return index
    }

    /// Whether `bytes` are exactly the UTF-8 bytes of `key`. Used by
    /// generated code inside a ``readKey(matchedBy:)`` closure to match a
    /// wire key against a field name known at compile time.
    @inlinable
    public static func key(_ bytes: UnsafeBufferPointer<UInt8>, matches key: StaticString) -> Bool {
        key.withUTF8Buffer { expected in
            bytes.count == expected.count
                && (bytes.isEmpty
                    || memcmp(bytes.baseAddress!, expected.baseAddress!, bytes.count) == 0)
        }
    }

    /// Packs `count` bytes of `bytes` starting at `offset` into a `UInt64`,
    /// first byte in the least significant position. Generated code inside a
    /// ``readKey(matchedBy:)`` closure switches on the wire key's length and
    /// then compares these chunks against constants computed at macro
    /// expansion time, so matching a field name costs one integer comparison
    /// per 8 bytes of key instead of a `memcmp` call per candidate.
    ///
    /// `count` must be 1...8 and `offset + count` must not exceed
    /// `bytes.count`; generated callers guarantee both by switching on
    /// `bytes.count` first.
    @inlinable
    @inline(__always)
    public static func keyChunk(
        _ bytes: UnsafeBufferPointer<UInt8>, offset: Int, count: Int
    ) -> UInt64 {
        assert(count >= 1 && count <= 8 && offset >= 0 && offset + count <= bytes.count)
        let base = UnsafeRawPointer(bytes.baseAddress.unsafelyUnwrapped)
        if count == 8 {
            return UInt64(littleEndian: base.loadUnaligned(fromByteOffset: offset, as: UInt64.self))
        }
        var value: UInt64 = 0
        for index in 0..<count {
            value |= UInt64(base.load(fromByteOffset: offset + index, as: UInt8.self)) << (index * 8)
        }
        return value
    }

    // MARK: Containers and extensions

    /// Reads an array header, enters the container, and returns the element
    /// count. The count is validated against the remaining input (each
    /// element takes at least one byte), so it is safe to reserve capacity
    /// for. Call ``endContainer()`` after reading the elements.
    @inlinable
    public mutating func readArrayHeader() throws(MessagePackError) -> Int {
        guard let count = try parser.readRawArrayHeader() else {
            throw MessagePackError.typeMismatch(expected: "array", format: try parser.peekFormat())
        }
        guard count <= parser.count - parser.offset else {
            throw MessagePackError.insufficientData
        }
        try enterContainer()
        return count
    }

    /// Reads a map header, enters the container, and returns the entry count.
    /// The count is validated against the remaining input (each entry takes
    /// at least two bytes), so it is safe to reserve capacity for. Call
    /// ``endContainer()`` after reading the entries.
    @inlinable
    public mutating func readMapHeader() throws(MessagePackError) -> Int {
        guard let count = try parser.readRawMapHeader() else {
            throw MessagePackError.typeMismatch(expected: "map", format: try parser.peekFormat())
        }
        guard count <= (parser.count - parser.offset) / 2 else {
            throw MessagePackError.insufficientData
        }
        try enterContainer()
        return count
    }

    @inlinable
    mutating func enterContainer() throws(MessagePackError) {
        guard depth < MessagePackReader.maxDepth else {
            throw MessagePackError.depthLimitExceeded
        }
        depth += 1
    }

    /// Marks the container most recently entered by ``readArrayHeader()`` /
    /// ``readMapHeader()`` as fully read. Generated `init(messagePack:)`
    /// implementations and the collection conformances call this after their
    /// element loops; hand-written conformances that read container headers
    /// must do the same, or long sequences of containers will exhaust
    /// ``maxDepth``. (Not calling it on error paths is fine — decoding
    /// aborts anyway.)
    @inlinable
    public mutating func endContainer() {
        if depth > 0 {
            depth -= 1
        }
    }

    /// Reads an extension value (type code and payload).
    @inlinable
    public mutating func readExt() throws(MessagePackError) -> (type: Int8, data: Data) {
        guard let value = try parser.readRawExt() else {
            throw MessagePackError.typeMismatch(expected: "ext", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads a timestamp (ext type -1).
    @inlinable
    public mutating func readTimestamp() throws(MessagePackError) -> MessagePackTimestamp {
        // The payload is read in place: a timestamp needs no `Data` of its own.
        guard let ext = try parser.readRawExtBytes() else {
            throw MessagePackError.typeMismatch(expected: "ext", format: try parser.peekFormat())
        }
        guard ext.type == MessagePackTimestamp.extType, let timestamp = MessagePackTimestamp(payload: ext.bytes) else {
            throw MessagePackError.invalidTimestamp
        }
        return timestamp
    }

    /// Skips one complete value (including nested containers).
    @inlinable
    public mutating func skipValue() throws(MessagePackError) {
        try parser.skipValue()
    }

    /// Reads a whole value tree as a ``MessagePackValue``. Nesting beyond
    /// ``MessagePackSerializer``'s depth limit throws
    /// ``MessagePackError/depthLimitExceeded``.
    public mutating func readValue() throws(MessagePackError) -> MessagePackValue {
        try parser.parseValue()
    }
}
