import Foundation

/// A streaming MessagePack output buffer, used by ``MessagePackSerializable``
/// conformances (typically generated by the `@MessagePackSerializable` macro)
/// to emit values.
///
/// Writing is a single pass into a growable raw buffer; ``finish()`` hands the
/// buffer to the returned `Data` without copying. All integers, strings, and
/// containers are written with the smallest wire format that represents them,
/// so the output is byte-identical to ``MessagePackSerializer`` and
/// ``MessagePackEncoder`` for equivalent values.
///
/// The writer is noncopyable: it owns a raw buffer whose ownership moves into
/// the returned `Data`, so a copy escaping a `serialize(into:)`
/// implementation could never be used safely.
public struct MessagePackWriter: ~Copyable {
    @usableFromInline
    var buffer: MessagePackScratchBuffer

    @usableFromInline
    init(initialCapacity: Int) {
        self.buffer = MessagePackScratchBuffer(initialCapacity: initialCapacity)
    }

    /// Wraps the buffer in a `Data` without copying.
    @usableFromInline
    consuming func finish() -> Data {
        let buffer = self.buffer
        return Data(
            bytesNoCopy: buffer.base,
            count: buffer.offset,
            deallocator: .custom { pointer, _ in pointer.deallocate() }
        )
    }

    // MARK: Scalars

    /// Writes a MessagePack nil.
    @inlinable
    public mutating func writeNil() {
        buffer.writeNil()
    }

    @inlinable
    public mutating func write(_ value: Bool) {
        buffer.writeBool(value)
    }

    /// Writes a signed integer using the smallest format that represents it.
    @inlinable
    public mutating func write(_ value: Int64) {
        buffer.writeInt(value)
    }

    @inlinable
    public mutating func write(_ value: Int) { buffer.writeInt(Int64(value)) }

    @inlinable
    public mutating func write(_ value: Int8) { buffer.writeInt(Int64(value)) }

    @inlinable
    public mutating func write(_ value: Int16) { buffer.writeInt(Int64(value)) }

    @inlinable
    public mutating func write(_ value: Int32) { buffer.writeInt(Int64(value)) }

    /// Writes an unsigned integer using the smallest format that represents it.
    @inlinable
    public mutating func write(_ value: UInt64) {
        buffer.writeUInt(value)
    }

    @inlinable
    public mutating func write(_ value: UInt) { buffer.writeUInt(UInt64(value)) }

    @inlinable
    public mutating func write(_ value: UInt8) { buffer.writeUInt(UInt64(value)) }

    @inlinable
    public mutating func write(_ value: UInt16) { buffer.writeUInt(UInt64(value)) }

    @inlinable
    public mutating func write(_ value: UInt32) { buffer.writeUInt(UInt64(value)) }

    @inlinable
    public mutating func write(_ value: Float) {
        buffer.writeFloat(value)
    }

    /// Writes a float 32 when it holds `value` exactly, else a float 64.
    @inlinable
    public mutating func write(_ value: Double) {
        buffer.writeDouble(value)
    }

    @inlinable
    public mutating func write(_ value: String) {
        buffer.writeString(value)
    }

    /// Writes `value` as MessagePack binary (bin 8/16/32).
    @inlinable
    public mutating func write(_ value: Data) {
        buffer.writeBinary(value)
    }

    /// Writes a map key known at compile time. Generated `serialize(into:)`
    /// implementations use this for field names; it copies the literal's
    /// UTF-8 bytes directly, bypassing `String` bridging.
    @inlinable
    public mutating func writeKey(_ key: StaticString) {
        key.withUTF8Buffer { utf8 in
            buffer.writeStringHeader(byteCount: utf8.count)
            if let baseAddress = utf8.baseAddress {
                buffer.writeBytes(baseAddress, count: utf8.count)
            }
        }
    }

    /// Writes `count` wire bytes packed little-endian into `word` (the first
    /// wire byte in the least significant position; bytes above `count` must
    /// be zero). Generated `serialize(into:)` implementations use this to
    /// emit a map header and precomputed field-name strings as a single
    /// 8-byte store instead of a header branch and a byte copy per key.
    /// `count` must be 1...8.
    @inlinable
    public mutating func writeRaw(_ word: UInt64, count: Int) {
        assert(count >= 1 && count <= 8)
        buffer.ensure(8)
        buffer.base.storeBytes(of: word.littleEndian, toByteOffset: buffer.offset, as: UInt64.self)
        buffer.offset += count
    }

    // MARK: Containers and extensions

    /// Writes an array header. Exactly `count` values must be written after it.
    @inlinable
    public mutating func writeArrayHeader(count: Int) {
        buffer.writeArrayHeader(count: count)
    }

    /// Writes a map header. Exactly `count` key-value pairs (2 × `count`
    /// values) must be written after it.
    @inlinable
    public mutating func writeMapHeader(count: Int) {
        buffer.writeMapHeader(count: count)
    }

    /// Writes an extension value with the given type code and payload.
    @inlinable
    public mutating func writeExt(type: Int8, data: Data) {
        buffer.writeExt(type: type, data: data)
    }

    /// Writes a timestamp as the spec's ext type -1.
    @inlinable
    public mutating func write(_ value: MessagePackTimestamp) {
        buffer.writeExt(type: MessagePackTimestamp.extType, data: value.data)
    }

    /// Writes a whole ``MessagePackValue`` tree.
    public mutating func write(_ value: MessagePackValue) {
        buffer.write(value)
    }
}
